collections:
  dates:
    output: true

defaults:
  - scope:
      path: ""
      type: "dates"
    values:
      layout: "date"
  - scope:
      path: ""
    values:
      layout: "default"
domain: diabolosnantes.fr
url: https://www.diabolosnantes.fr
baseurl:

responsive_image:
  template: _includes/image.html
  sizes:
    - width: 301
    - width: 400
