collections:
  dates:
    output: true
  spectacles:
    output: false

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "dates"
    values:
      layout: "date"
  - scope:
      path: ""
      type: "spectacles"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

domain: diabolosnantes.fr
url: https://www.diabolosnantes.fr
baseurl:
